modLoader="javafml"
loaderVersion="[45,)"
license="The Apache License, Version 2.0"

[[mods]]
modId="minemention"
version="${file.jarVersion}"
displayName="Minemention"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minemention"
updateJSONURL="https://assets.melanx.de/updates/minemention.json"
authors="noeppi_noeppi"
description="""
"""

[[dependencies.minemention]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minemention]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minemention]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.4-4.4.1,)"
    ordering="NONE"
    side="BOTH"
