modLoader="javafml"
loaderVersion="[47,)"
license="The Apache License, Version 2.0"

[[mods]]
modId="minemention"
version="${version}"
displayName="Minemention"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minemention"
updateJSONURL="https://assets.melanx.de/updates/minemention.json"
authors="noeppi_noeppi"
description="""
"""

[[dependencies.minemention]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minemention]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minemention]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.1,)"
    ordering="NONE"
    side="BOTH"
